-- Sunday Pickleball Scheduler — Supabase setup / migration
-- Run this entire script in the Supabase SQL Editor.
-- Safe to re-run — uses IF NOT EXISTS / ON CONFLICT DO NOTHING.
--
-- Columns, types, primary keys and NOT NULL constraints below were generated by
-- introspecting the live database's PostgREST schema, so they reflect what is
-- actually deployed. The previous version of this file had drifted badly: it was
-- missing two tables (players, session) and ten columns, and its final migration
-- block read from a `players` table it never created — so the script could not
-- run at all against an empty project.
--
-- Verified: this script applies cleanly to an empty PostgreSQL 14 database,
-- is idempotent across repeated runs, and accepts a full data restore.
--
-- Column DEFAULTS are carried over from the previous version of this file and
-- are NOT independently verified — PostgREST does not expose defaults. Columns
-- added to the database after that version have no default declared here and
-- may have one in production. Indexes beyond primary keys, check constraints,
-- foreign keys and triggers are likewise not represented.

-- ── contacts — unified contact + player record ──
-- Column order matches the live table.
create table if not exists contacts (
  id             bigint primary key,
  name           text not null,
  phone          text not null default '',
  rsvp           text,
  invited        boolean not null default true,
  created_at     timestamptz default now(),
  is_player      boolean not null default false,
  gender         text not null default 'M',
  dupr           numeric(4,2) not null default 3.5,
  dupr_url       text,
  dupr_updated   timestamptz,
  wins           integer not null default 0,
  losses         integer not null default 0,
  partner_stats  jsonb default '{}'::jsonb,
  avail_days     jsonb
);

-- ── players — legacy table, superseded by contacts ──
-- Still present in production with live rows; retained so this script can
-- recreate the database and so the migration block at the end has a source.
create table if not exists players (
  id             bigint primary key,
  name           text not null,
  gender         text not null,
  dupr           numeric(4,2) not null,
  dupr_url       text,
  dupr_updated   timestamptz,
  wins           integer not null default 0,
  losses         integer not null default 0,
  partner_stats  jsonb default '{}'::jsonb,
  created_at     timestamptz default now()
);

-- ── schedules ──
create table if not exists schedules (
  id                 bigint primary key,
  name               text not null default 'Sunday Schedule',
  date               text not null default '',
  selected           jsonb default '[]'::jsonb,
  matches            jsonb default '[]'::jsonb,
  generated          boolean default false,
  rounds             integer default 10,
  created_at         timestamptz default now(),
  updated_at         timestamptz default now(),
  raw_date           text,
  mode               text default 'auto',
  rsvps              json,            -- json, not jsonb, in the live database
  fixed_matches      jsonb,
  rsvp_cutoff        timestamptz,
  pairs              jsonb,
  courts             integer,
  waitlist_override  boolean,
  rsvp_log           jsonb,
  ai_notes           text
);

-- ── session — single-row working state, not covered by the old script ──
create table if not exists session (
  id          integer primary key,
  selected    jsonb,
  matches     jsonb,
  generated   boolean,
  date        text,
  updated_at  timestamptz
);

-- ── settings — singleton row, id = 1 ──
create table if not exists settings (
  id         integer primary key default 1,
  pin_hash   text default '',
  invite_msg text default 'Hey everyone! Pickleball this Sunday — who''s in? Reply YES to be added to the schedule, NO if you can''t make it. See you there! 🏓',
  updated_at timestamptz default now()
);

insert into settings (id) values (1) on conflict (id) do nothing;

-- ── Row Level Security ──
-- The application reaches Postgres only through the Netlify functions using the
-- service_role key, which bypasses RLS. These policies are permissive and are
-- not a meaningful access control layer; tightening them is a separate change.
alter table contacts  enable row level security;
alter table schedules enable row level security;
alter table settings  enable row level security;

drop policy if exists "service full access" on contacts;
drop policy if exists "service full access" on schedules;
drop policy if exists "service full access" on settings;

create policy "service full access" on contacts  for all using (true) with check (true);
create policy "service full access" on schedules for all using (true) with check (true);
create policy "service full access" on settings  for all using (true) with check (true);

-- ── Note on the legacy players → contacts migration ──
-- Earlier versions of this file ended with an INSERT that copied every row from
-- players into contacts. That migration has already been applied in production
-- and has been REMOVED rather than kept, because re-running it is destructive in
-- a non-obvious way:
--
--   players currently holds 16 rows; 13 have matching contacts. The other 3 are
--   people who were deleted from contacts. Re-running the migration would
--   silently recreate them, and this file's own header invites re-running it.
--
-- If the remaining players rows ever need folding in, do it deliberately as a
-- one-off statement after confirming which ids should come back — not as part
-- of a script described as safe to re-run.
